version: "3.9"

services:
  mcp-client:
    build:
      context: ./mcp-client
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    container_name: mcp-client
    ports:
      - "8000:8000"
    depends_on:
      - mcp-server
    networks:
      - mcp-network

  mcp-server:
    build:
      context: .
      dockerfile: ./mcp-server/Dockerfile
      platforms:
        - linux/amd64
    container_name: mcp-server
    command: ["python", "mcp_server.py"]
    ports:
      - "8001:8001"
    depends_on:
      - mariadb
      - opa
      - qdrant
    networks:
      - mcp-network

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    container_name: ui
    ports:
      - "8501:8501"
    depends_on:
      - mcp-client
    networks:
      - mcp-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    platform: linux/amd64
    ports:
      - "6333:6333"
    volumes:
      - ./data/qdrant:/qdrant/storage
    networks:
      - mcp-network

  opa:
    image: openpolicyagent/opa:latest
    container_name: opa
    platform: linux/amd64
    command: ["run", "--server"]
    ports:
      - "8181:8181"
    networks:
      - mcp-network

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: opa_db
    ports:
      - "3306:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge
